services:
  cowrie:
    image: cowrie/cowrie
    ports:
      - "2224:2224"  # SSH (updated port)
      - "2225:2225"  # Telnet (updated port)
    volumes:
      - ./cowrie/cowrie-git/etc:/cowrie/cowrie-git/etc
      - ./cowrie/cowrie-git/var:/cowrie/cowrie-git/var
    networks:
      - nids_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./cowrie/cowrie-git/var/log:/cowrie_logs:ro
      - ./cowrie/cowrie-git/etc:/cowrie/cowrie-git/etc:ro  # Added Cowrie config access
    environment:
      - COWRIE_LOG_PATH=/cowrie_logs/cowrie.json
    depends_on:
      - cowrie
    networks:
      - nids_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - nids_network

  caddy:
    image: caddy:2
    container_name: nidstoknow-caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
    networks:
      - nids_network

networks:
  nids_network:
    driver: bridge 

volumes:
  caddy_data:
  caddy_config: