services:
  mysql:
    image: mysql:8.0
    container_name: nidstoknow-mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-${DB_PASSWORD}}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 12

  backend:
    environment:
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - COWRIE_LOG_PATH=${COWRIE_LOG_PATH:-/cowrie/cowrie-git/var/log/cowrie.json}
      - DEV_MODE=${DEV_MODE:-false}
    depends_on:
      mysql:
        condition: service_healthy
    command: ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]
    restart: unless-stopped

volumes:
  mysql_data:
    name: nidstoknow-mysql-data
