services:
  cowrie:
    image: cowrie/cowrie
    ports:
      - "2224:2224"  # SSH (updated port)
      - "2225:2225"  # Telnet (updated port)
    volumes:
      - ./cowrie/cowrie-git/etc:/cowrie/cowrie-git/etc
      - ./cowrie/cowrie-git/var:/cowrie/cowrie-git/var
    networks:
      - nids_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./cowrie/cowrie-git/var/log:/cowrie_logs:ro
      - ./cowrie/cowrie-git/etc:/cowrie/cowrie-git/etc:ro  # Added Cowrie config access
    environment:
      - COWRIE_LOG_PATH=/cowrie_logs/cowrie.json
    depends_on:
      - cowrie
    networks:
      - nids_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Serve frontend on standard HTTP port for ALB/Route53
    volumes:
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - nids_network

networks:
  nids_network:
    driver: bridge 